### ISSUE TITLE
rerunning import cell kills splits

### ISSUE THREAD

**Issue by christopher-besch** [kolibril13/jupyter-splitview#14]

**Comment by christopher-besch** [comment]
@kolibril13, as far as I can tell Python doesn't like double imports. Therefore it ignores the second call to `import jupyter_splitview`. The issue is that Jupyter deletes all cell output when you rerun it and because the second run is ignored, the juxtapose.js JS and CSS is missing and the splits break.
Do you know any permanent way of adding HTML to a notebook?

**Comment by christopher-besch** [comment]
Of course the easy way "fixing" this is to include the JS and CSS every time you need it. But this really bloats your file size like hell, so please don't do that.

**Comment by kolibril13** [comment]
Thanks for investigating this!
I'll ask some people in the Jupyter widget gitter if there is a way of permanent adding HTML to a notebook

**Comment by christopher-besch** [comment]
An alternative solution would be a way of always calling the import. I don't think there's a very clean solution to this, though.
